// types generated by chatgpt

// Core Big Five Personality Traits
export type BigFiveTraits = {
    openness: number;           // 0 to 1
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
};

// Emotional Characteristics
export type EmotionalTraits = {
    empathy: number;
    humor: number;
    confidence: number;
    patience: number;
    resilience: number;
    courage: number;
    impulsiveness: number;      // Higher means more impulsive
};

// Social Characteristics
export type SocialTraits = {
    altruism: number;
    cooperation: number;
    assertiveness: number;
    dominance: number;
    politeness: number;
};

// Cognitive Characteristics
export type CognitiveTraits = {
    curiosity: number;
    creativity: number;
    learningRate: number;       // 0 to 1
    workingMemory: number;      // Scale of working memory (0 to 1)
    attentionSpan: number;      // 0 to 1
    decisionStyle: 'analytical' | 'intuitive' | 'balanced';
    biasTendency: number;       // How likely they rely on biases (0 to 1)
};

// Moral Characteristics
export type MoralTraits = {
    integrity: number;
    fairness: number;
    loyalty: number;
    responsibility: number;
};

// Combined Human Profile
export type HumanCharacterProfile = {
    bigFive?: BigFiveTraits;
    emotional?: EmotionalTraits;
    social?: SocialTraits;
    cognitive?: CognitiveTraits;
    moral?: MoralTraits;
};
